name: ct484_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=3.1.3 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.6
    provider: ^6.1.2
    flutter_dotenv: ^5.1.0
    http: ^1.2.0
    shared_preferences: ^2.2.2
    firebase_core: ^2.27.0
    firebase_auth: ^4.17.8
    flex_color_scheme: ^7.3.1
    google_fonts: 6.1.0
    another_flushbar: ^1.12.30
    google_sign_in: ^6.2.1
    flutter_facebook_auth: ^6.2.0
    ionicons: ^0.2.2
    image_picker: ^1.0.7
    cloud_firestore: ^4.15.8
    firebase_storage: ^11.7.0
    cached_network_image: ^3.3.1
    scrollable_positioned_list: ^0.3.8

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true
    assets:
        - .env
        - assets/

